[toolchain]
version = "1.91.0"
channel = "stable"
profile = "default"

components = ["cargo", "clippy", "rust-analyzer", "rust-src", "rust-std", "rustc", "rustfmt"]

targets = [
  # Linux
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",

  # Darwin
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
]
