elide:
  gvm:
    enabled: true
    languages: ["JS"]
    defer: true
    js:
      enabled: true
      wasm: true
      interactive: false

micronaut:
  application:
    name: elide
    default-charset: utf-8

  executors:
    type: FIXED
    default:
      threads: 1
    io:
      threads: 2
    scheduled:
      threads: 1

jackson:
  serialization:
    ORDER_MAP_ENTRIES_BY_KEYS: true

## Performance
netty.default.allocator.max-order: 3
netty.resource-leak-detector-level: DISABLED
micronaut.server.netty.use-native-transport: true
micronaut.netty.event-loops.*.prefer-native-transport: true
micronaut.server.netty.parent.prefer-native-transport: true
micronaut.server.netty.worker.prefer-native-transport: true
micronaut.server.netty.worker.event-loop-group: native
micronaut.netty.event-loops.default.prefer-native-transport: true
micronaut.netty.event-loops.native.prefer-native-transport: true
micronaut.netty.event-loops.native.num-threads: 16
