config:
  validation: true
  warningsAsErrors: false

processors:
  active: true

console-reports:
  active: true
  exclude:
    - "ProjectStatisticsReport"
    - "ComplexityReport"
    - "NotificationReport"
    - "FindingsReport"
    - "FileBasedFindingsReport"
  #  - 'LiteFindingsReport'

output-reports:
  active: true
  exclude:
   - 'SarifOutputReport'
   - 'XmlOutputReport'
   - 'HtmlOutputReport'

comments:
  active: true
  AbsentOrWrongFileLicense:
    active: false
    licenseTemplateFile: "license.template"
    licenseTemplateIsRegex: false
  CommentOverPrivateFunction:
    active: false
  CommentOverPrivateProperty:
    active: false
  DeprecatedBlockTag:
    active: false
  EndOfSentenceFormat:
    active: false
    endOfSentenceFormat: '([.?!][ \t\n\r\f<])|([.?!:]$)'
  OutdatedDocumentation:
    active: false
    matchTypeParameters: true
    matchDeclarationsOrder: true
    allowParamOnConstructorProperties: false
  UndocumentedPublicClass:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  UndocumentedPublicFunction:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
  UndocumentedPublicProperty:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]

complexity:
  active: true
  ComplexCondition:
    active: false
  ComplexInterface:
    active: false
    includeStaticDeclarations: false
    includePrivateDeclarations: false
  CyclomaticComplexMethod:
    active: false
    ignoreSingleWhenExpression: false
    ignoreSimpleWhenEntries: false
    ignoreNestingFunctions: false
    nestingFunctions:
      - "also"
      - "apply"
      - "forEach"
      - "isNotNull"
      - "ifNull"
      - "let"
      - "run"
      - "use"
      - "with"
  LabeledExpression:
    active: false
    ignoredLabels: []
  LargeClass:
    active: false
  LongMethod:
    active: false
  LongParameterList:
    active: true
    ignoreDefaultParameters: false
    ignoreDataClasses: true
    ignoreAnnotatedParameter: []
  MethodOverloading:
    active: false
  NamedArguments:
    active: false
    ignoreArgumentsMatchingNames: false
  NestedBlockDepth:
    active: true
  ReplaceSafeCallChainWithRun:
    active: false
  StringLiteralDuplication:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    ignoreAnnotation: true
    ignoreStringsRegex: "$^"
  TooManyFunctions:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    ignoreDeprecated: false
    ignorePrivate: false
    ignoreOverridden: false

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: false
  InjectDispatcher:
    active: false
    dispatcherNames:
      - "IO"
      - "Default"
      - "Unconfined"
  RedundantSuspendModifier:
    active: false
  SleepInsteadOfDelay:
    active: false
  SuspendFunWithCoroutineScopeReceiver:
    active: false
  SuspendFunWithFlowReturnType:
    active: false

empty-blocks:
  active: true
  EmptyCatchBlock:
    active: true
    allowedExceptionNameRegex: "_|(ignore|expected).*"
  EmptyClassBlock:
    active: false
  EmptyDefaultConstructor:
    active: true
  EmptyDoWhileBlock:
    active: true
  EmptyElseBlock:
    active: true
  EmptyFinallyBlock:
    active: true
  EmptyForBlock:
    active: true
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: false
  EmptyIfBlock:
    active: true
  EmptyInitBlock:
    active: true
  EmptySecondaryConstructor:
    active: true
  EmptyTryBlock:
    active: true
  EmptyWhenBlock:
    active: true
  EmptyWhileBlock:
    active: true

exceptions:
  active: true
  ExceptionRaisedInUnexpectedLocation:
    active: true
    methodNames:
      - "equals"
      - "finalize"
      - "hashCode"
      - "toString"
  InstanceOfCheckForException:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
  NotImplementedDeclaration:
    active: false
  ObjectExtendsThrowable:
    active: false
  PrintStackTrace:
    active: true
  RethrowCaughtException:
    active: true
  ReturnFromFinally:
    active: true
    ignoreLabeled: false
  SwallowedException:
    active: true
    ignoredExceptionTypes:
      - "InterruptedException"
      - "MalformedURLException"
      - "NumberFormatException"
      - "ParseException"
    allowedExceptionNameRegex: "_|(ignore|expected).*"
  ThrowingExceptionFromFinally:
    active: true
  ThrowingExceptionInMain:
    active: false
  ThrowingExceptionsWithoutMessageOrCause:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    exceptions:
      - "ArrayIndexOutOfBoundsException"
      - "Exception"
      - "IllegalArgumentException"
      - "IllegalMonitorStateException"
      - "IllegalStateException"
      - "IndexOutOfBoundsException"
      - "NullPointerException"
      - "RuntimeException"
      - "Throwable"
  ThrowingNewInstanceOfSameException:
    active: true
  TooGenericExceptionCaught:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
        "**/embedded/api/**",
        "**/embedded/*",
      ]
    exceptionNames:
      - "ArrayIndexOutOfBoundsException"
      - "Error"
      - "Exception"
      - "IllegalMonitorStateException"
      - "IndexOutOfBoundsException"
      - "NullPointerException"
      - "RuntimeException"
      - "Throwable"
    allowedExceptionNameRegex: "_|(ignore|expected).*"
  TooGenericExceptionThrown:
    active: true
    exceptionNames:
      - "Error"
      - "Exception"
      - "RuntimeException"
      - "Throwable"

naming:
  active: true
  BooleanPropertyNaming:
    active: false
    allowedPattern: "^(is|has|are)"
  ClassNaming:
    active: true
    classPattern: "[A-Z][a-zA-Z0-9]*"
  ConstructorParameterNaming:
    active: true
    parameterPattern: "[a-z][A-Za-z0-9]*"
    privateParameterPattern: "[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"
  EnumNaming:
    active: true
    enumEntryPattern: "[A-Z][_a-zA-Z0-9]*"
  ForbiddenClassName:
    active: false
    forbiddenName: []
  FunctionNaming:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    functionPattern: "[a-z][a-zA-Z0-9]*"
    excludeClassPattern: "$^"
  FunctionParameterNaming:
    active: true
    parameterPattern: "[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"
  InvalidPackageDeclaration:
    active: false
    rootPackage: ""
    requireRootInDeclaration: false
  LambdaParameterNaming:
    active: false
    parameterPattern: "[a-z][A-Za-z0-9]*|_"
  MatchingDeclarationName:
    active: false
    mustBeFirst: true
  MemberNameEqualsClassName:
    active: true
    ignoreOverridden: true
  NoNameShadowing:
    active: false
  NonBooleanPropertyPrefixedWithIs:
    active: false
  ObjectPropertyNaming:
    active: true
    constantPattern: "[A-Za-z][_A-Za-z0-9]*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "(_)?[A-Za-z][_A-Za-z0-9]*"
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][A-Za-z0-9]*)*'
  TopLevelPropertyNaming:
    active: true
    constantPattern: "[A-Z][_A-Z0-9]*"
    propertyPattern: "[A-Za-z][_A-Za-z0-9]*"
    privatePropertyPattern: "_?[A-Za-z][_A-Za-z0-9]*"
  VariableMaxLength:
    active: false
    maximumVariableNameLength: 64
  VariableMinLength:
    active: false
    minimumVariableNameLength: 1
  VariableNaming:
    active: true
    variablePattern: "[a-z][A-Za-z0-9]*"
    privateVariablePattern: "(_)?[a-z][A-Za-z0-9]*"
    excludeClassPattern: "$^"

performance:
  active: true
  ArrayPrimitive:
    active: true
  ForEachOnRange:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
  SpreadOperator:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
  UnnecessaryTemporaryInstantiation:
    active: true

potential-bugs:
  active: true
  AvoidReferentialEquality:
    active: false
    forbiddenTypePatterns:
      - "kotlin.String"
  CastToNullableType:
    active: false
  Deprecation:
    active: false
  DontDowncastCollectionTypes:
    active: false
  DoubleMutabilityForCollection:
    active: false
    mutableTypes:
      - "kotlin.collections.MutableList"
      - "kotlin.collections.MutableMap"
      - "kotlin.collections.MutableSet"
      - "java.util.ArrayList"
      - "java.util.LinkedHashSet"
      - "java.util.HashSet"
      - "java.util.LinkedHashMap"
      - "java.util.HashMap"
  ElseCaseInsteadOfExhaustiveWhen:
    active: false
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  EqualsWithHashCodeExist:
    active: true
  ExitOutsideMain:
    active: false
  ExplicitGarbageCollectionCall:
    active: true
  HasPlatformType:
    active: false
  IgnoredReturnValue:
    active: false
    restrictToConfig: true
    returnValueAnnotations:
      - "*.CheckResult"
      - "*.CheckReturnValue"
    ignoreReturnValueAnnotations:
      - "*.CanIgnoreReturnValue"
    ignoreFunctionCall: []
  ImplicitDefaultLocale:
    active: true
  ImplicitUnitReturnType:
    active: false
    allowExplicitReturnType: true
  InvalidRange:
    active: true
  IteratorHasNextCallsNextMethod:
    active: true
  IteratorNotThrowingNoSuchElementException:
    active: true
  LateinitUsage:
    active: false
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    ignoreOnClassesPattern: ""
  MapGetWithNotNullAssertionOperator:
    active: false
  MissingPackageDeclaration:
    active: false
    excludes: ["**/*.kts"]
  NullCheckOnMutableProperty:
    active: false
  NullableToStringCall:
    active: false
  UnconditionalJumpStatementInLoop:
    active: false
  UnnecessaryNotNullOperator:
    active: true
  UnnecessarySafeCall:
    active: true
  UnreachableCatchBlock:
    active: false
  UnreachableCode:
    active: true
  UnsafeCallOnNullableType:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
  UnsafeCast:
    active: true
  UnusedUnaryOperator:
    active: false
  UselessPostfixExpression:
    active: false
  WrongEqualsTypeParameter:
    active: true

style:
  active: true
  CanBeNonNullable:
    active: false
  ClassOrdering:
    active: false
  CollapsibleIfStatements:
    active: false
  DataClassContainsFunctions:
    active: false
    conversionFunctionPrefix:
      -  "to"
  DataClassShouldBeImmutable:
    active: false
  DestructuringDeclarationWithTooManyEntries:
    active: false
    maxDestructuringEntries: 3
  EqualsNullCall:
    active: true
  EqualsOnSignatureLine:
    active: false
  ExplicitCollectionElementAccessMethod:
    active: false
  ExplicitItLambdaParameter:
    active: false
  ExpressionBodySyntax:
    active: false
    includeLineWrapping: false
  ForbiddenComment:
    active: true
    allowedPatterns: ""
  ForbiddenImport:
    active: false
    imports: []
    forbiddenPatterns: ""
  ForbiddenMethodCall:
    active: false
    methods:
      - "kotlin.io.print"
      - "kotlin.io.println"
  ForbiddenVoid:
    active: false
    ignoreOverridden: false
    ignoreUsageInGenerics: false
  FunctionOnlyReturningConstant:
    active: true
    ignoreOverridableFunction: true
    ignoreActualFunction: true
    excludedFunctions: []
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 2
  MagicNumber:
    active: true
    excludes:
      [
        "**/test/**",
        "**/androidTest/**",
        "**/commonTest/**",
        "**/jvmTest/**",
        "**/jsTest/**",
        "**/iosTest/**",
      ]
    ignoreNumbers:
      - "-5"
      - "-4"
      - "-3"
      - "-2"
      - "-1"
      - "0"
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "7"
      - "8"
      - "9"
      - "10"
    ignoreHashCodeFunction: true
    ignorePropertyDeclaration: false
    ignoreLocalVariableDeclaration: false
    ignoreConstantDeclaration: true
    ignoreCompanionObjectPropertyDeclaration: true
    ignoreAnnotation: false
    ignoreNamedArgument: true
    ignoreEnums: false
    ignoreRanges: false
    ignoreExtensionFunctions: true
  MandatoryBracesLoops:
    active: false
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  ModifierOrder:
    active: true
  MultilineLambdaItParameter:
    active: false
  NestedClassesVisibility:
    active: true
  NewLineAtEndOfFile:
    active: true
  NoTabs:
    active: false
  ObjectLiteralToLambda:
    active: false
  OptionalAbstractKeyword:
    active: true
  OptionalUnit:
    active: false
  PreferToOverPairSyntax:
    active: false
  ProtectedMemberInFinalClass:
    active: true
  RedundantExplicitType:
    active: false
  RedundantHigherOrderMapUsage:
    active: false
  ReturnCount:
    active: true
    max: 3
    excludedFunctions:
      - "equals"
    excludeLabeled: false
    excludeReturnFromLambda: true
    excludeGuardClauses: false
  SafeCast:
    active: true
  SerialVersionUIDInSerializableClass:
    active: true
  ThrowsCount:
    active: true
    max: 3
    excludeGuardClauses: false
  TrailingWhitespace:
    active: false
  UnderscoresInNumericLiterals:
    active: false
    acceptableLength: 4
    allowNonStandardGrouping: false
  UnnecessaryAnnotationUseSiteTarget:
    active: false
  UnnecessaryApply:
    active: true
  UnnecessaryFilter:
    active: false
  UnnecessaryInheritance:
    active: true
  UnnecessaryInnerClass:
    active: false
  UnnecessaryLet:
    active: false
  UnnecessaryParentheses:
    active: false
  UnusedPrivateClass:
    active: true
  UseAnyOrNoneInsteadOfFind:
    active: false
  UseArrayLiteralsInAnnotations:
    active: false
  UseCheckNotNull:
    active: false
  UseCheckOrError:
    active: false
  UseDataClass:
    active: false
    allowVars: false
  UseEmptyCounterpart:
    active: false
  UseIfEmptyOrIfBlank:
    active: false
  UseIfInsteadOfWhen:
    active: false
  UseIsNullOrEmpty:
    active: false
  UseOrEmpty:
    active: false
  UseRequire:
    active: false
  UseRequireNotNull:
    active: false
  UselessCallOnNotNull:
    active: true
  UtilityClassWithPublicConstructor:
    active: true
  VarCouldBeVal:
    active: true
  WildcardImport:
    active: false

#libraries:
#  LibraryCodeMustSpecifyReturnType:
#    active: true
#    excludes: [ "**" ]
#  ForbiddenPublicDataClass:
#    active: true
#    excludes: [ "**" ]
#    ignorePackages:
#      - "*.internal"
#      - "*.internal.*"
#  LibraryEntitiesShouldNotBePublic:
#    active: true
#    excludes: ["**"]
